name: 监听 Push 打包部署

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  npm-build:
    name: Npm Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 安装依赖
      run: |
        npm install

    - name: 打包
      run: |
        npm run build

    - name: 部署
      uses: JamesIves/github-pages-deploy-action@v4
      with: 
        branch: main
        folder: dist
        
